# Generated by Django 3.2 on 2021-05-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busca_precos', '0002_alter_busca_periodicidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busca',
            name='site',
            field=models.CharField(choices=[('Kabum', 'KABUM')], max_length=254),
        ),
    ]
