# Generated by Django 3.2 on 2021-05-10 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('rg', models.CharField(max_length=11)),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=254)),
                ('site', models.CharField(choices=[('Kabum', 'KABUM')], max_length=254)),
                ('periodicidade', models.IntegerField(choices=[(24, 'todo dia'), (12, 'duas vezes ao dia'), (6, 'quatro vezes ao dia')])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_prices.client')),
            ],
        ),
    ]
