# Generated by Django 3.2 on 2021-05-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busca_precos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busca',
            name='periodicidade',
            field=models.IntegerField(choices=[(24, 'todo dia'), (12, 'duas vezes ao dia'), (6, 'quatro vezes ao dia')]),
        ),
    ]
